# Generated by Django 4.2.23 on 2025-07-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='domain',
            field=models.CharField(choices=[('IT', 'IT'), ('Non-IT', 'Non-IT'), ('Internship', 'Internship'), ('Government', 'Government')], default='IT', max_length=20),
        ),
    ]
